### ISSUE TITLE
Update the A-Record Public IP on Vagrant Reload

### ISSUE THREAD

**Issue by ichristo** [Yleisradio/vagrant-aws-extras#1]
If an EC2 image is halted and restarted, its public IP is reassigned.  The A-Record in Route53 should be updated to reflect the new IP.

**Comment by ichristo** [comment]
Error on my part.  Closing

**Comment by sebastiang** [comment]
I am still seeing this error; after a `vagrant halt`, a `vagrant up` results in a lovely error message. Perhaps I am using the provider incorrectly? 

```
override.aws_extras.record_zone = "adomain.net."
override.aws_extras.record_name = "app." + `whoami`.strip() + ".adomain.net."
override.aws_extras.record_type = "CNAME"
override.aws_extras.record_ttl = "60"
```

The error:

```
$ vagrant up
Bringing machine 'default' up with 'aws' provider...
==> default: Warning! The AWS provider doesn't support any of the Vagrant
==> default: high-level network configurations (`config.vm.network`). They
==> default: will be silently ignored. 
==> default: Starting the instance...
==> default: Waiting for instance to become "ready"...
==> default: Waiting for SSH to become available...
==> default: Machine is booted and ready for use!
/Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/expects.rb:6:in `response_call': InvalidChangeBatch => Tried to create resource record set [name='<the dans name>.', type='A'] but it already exists (Fog::DNS::AWS::Error)
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/response_parser.rb:8:in `response_call'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/connection.rb:372:in `response'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/connection.rb:236:in `request'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/connection.rb:256:in `rescue in request'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/connection.rb:204:in `request'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/connection.rb:256:in `rescue in request'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/connection.rb:204:in `request'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/connection.rb:256:in `rescue in request'
from /Users/sebastian/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/connection.rb:204:in `request'
from /Users/sebastian/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
from /Users/sebastian/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
from /Users/sebastian/.vagrant.d/gems/gems/fog-aws-0.6.0/lib/fog/aws/dns.rb:141:in `_request'
from /Users/sebastian/.vagrant.d/gems/gems/fog-aws-0.6.0/lib/fog/aws/dns.rb:136:in `request'
from /Users/sebastian/.vagrant.d/gems/gems/fog-aws-0.6.0/lib/fog/aws/requests/dns/change_resource_record_sets.rb:142:in `change_resource_record_sets'
from /Users/sebastian/.vagrant.d/gems/gems/fog-aws-0.6.0/lib/fog/aws/models/dns/record.rb:44:in `save'
from /Users/sebastian/.vagrant.d/gems/gems/fog-core-1.31.1/lib/fog/core/collection.rb:51:in `create'
from /Users/sebastian/.vagrant.d/gems/gems/vagrant-aws-extras-0.1.0/lib/vagrant-aws-extras/action/dns.rb:76:in `set'
from /Users/sebastian/.vagrant.d/gems/gems/vagrant-aws-extras-0.1.0/lib/vagrant-aws-extras/action/dns.rb:61:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/sebastian/.vagrant.d/gems/gems/vagrant-aws-extras-0.1.0/lib/vagrant-aws-extras/action/dns.rb:50:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/sebastian/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/read_ssh_info.rb:17:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/sebastian/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/sebastian/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/start_instance.rb:76:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/sebastian/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/elb_register_instance.rb:16:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/sebastian/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/sebastian/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```
